export type ItemStatus = "todo" | "done" | "snoozed"

export interface PackingItem {
  id: string
  name: string
  category: string
  status: ItemStatus
  ownerId?: string
}

export interface FamilyMember {
  id: string
  name: string
  avatar: string
  photo: string
  items: PackingItem[]
}

export const DEFAULT_CATEGORIES = [
  "Clothing",
  "Toiletries",
  "Electronics",
  "Documents",
  "Summer",
  "Accessories",
  "Health",
  "Entertainment",
  "Snacks",
  "Bedding",
  "Gear",
  "Toys",
  "Safety",
  "General",
]

export const CATEGORY_ICONS: Record<string, string> = {
  Clothing: "shirt",
  Toiletries: "droplets",
  Electronics: "zap",
  Documents: "file-text",
  Summer: "sun",
  Accessories: "watch",
  Health: "heart-pulse",
  Entertainment: "gamepad-2",
  Snacks: "cookie",
  Bedding: "bed-double",
  Gear: "wrench",
  Toys: "toy-brick",
  Safety: "shield-check",
  General: "package",
}

export const CATEGORY_COLORS: Record<string, string> = {
  Clothing: "bg-primary/10 text-primary",
  Toiletries: "bg-accent/15 text-accent",
  Electronics: "bg-warning/15 text-warning-foreground",
  Documents: "bg-muted text-muted-foreground",
  Summer: "bg-warning/15 text-warning-foreground",
  Accessories: "bg-primary/10 text-primary",
  Health: "bg-destructive/10 text-destructive",
  Entertainment: "bg-accent/15 text-accent",
  Snacks: "bg-warning/10 text-warning-foreground",
  Bedding: "bg-primary/10 text-primary",
  Gear: "bg-muted text-muted-foreground",
  Toys: "bg-accent/15 text-accent",
  Safety: "bg-destructive/10 text-destructive",
  General: "bg-muted text-muted-foreground",
}

function createItems(memberId: string, items: [string, string][]): PackingItem[] {
  return items.map(([name, category], i) => ({
    id: `${memberId}-${i}-${name.toLowerCase().replace(/\s/g, "-")}`,
    name,
    category,
    status: "todo" as ItemStatus,
    ownerId: memberId,
  }))
}

export const initialFamilyData: FamilyMember[] = [
  {
    id: "mom",
    name: "Mom",
    avatar: "M",
    photo: "/avatars/mom.jpg",
    items: createItems("mom", [
      ["Dresses (3)", "Clothing"],
      ["Tops (5)", "Clothing"],
      ["Shorts (2)", "Clothing"],
      ["Swimsuit", "Summer"],
      ["Cover-up", "Summer"],
      ["Pajamas", "Clothing"],
      ["Underwear (7)", "Clothing"],
      ["Sandals", "Clothing"],
      ["Sun hat", "Summer"],
      ["Sunglasses", "Summer"],
      ["Toothbrush", "Toiletries"],
      ["Skincare set", "Toiletries"],
      ["Shampoo & conditioner", "Toiletries"],
      ["Makeup bag", "Toiletries"],
      ["Sunscreen", "Toiletries"],
      ["Hair dryer", "Toiletries"],
      ["Phone charger", "Electronics"],
      ["Kindle", "Electronics"],
      ["Passport", "Documents"],
      ["Boarding passes", "Documents"],
      ["Hotel confirmation", "Documents"],
      ["Jewelry pouch", "Accessories"],
      ["Scarf", "Accessories"],
      ["Vitamins", "Health"],
      ["Allergy meds", "Health"],
    ]),
  },
  {
    id: "dad",
    name: "Dad",
    avatar: "D",
    photo: "/avatars/dad.jpg",
    items: createItems("dad", [
      ["T-shirts (5)", "Clothing"],
      ["Shorts (3)", "Clothing"],
      ["Jeans", "Clothing"],
      ["Swimsuit", "Summer"],
      ["Pajamas", "Clothing"],
      ["Underwear (7)", "Clothing"],
      ["Socks (5 pairs)", "Clothing"],
      ["Sunglasses", "Summer"],
      ["Flip flops", "Summer"],
      ["Sneakers", "Clothing"],
      ["Toothbrush", "Toiletries"],
      ["Toothpaste", "Toiletries"],
      ["Deodorant", "Toiletries"],
      ["Shampoo", "Toiletries"],
      ["Razor", "Toiletries"],
      ["Sunscreen", "Toiletries"],
      ["Phone charger", "Electronics"],
      ["Laptop", "Electronics"],
      ["Headphones", "Electronics"],
      ["Camera", "Electronics"],
      ["Passport", "Documents"],
      ["Boarding passes", "Documents"],
      ["Travel insurance", "Documents"],
      ["Watch", "Accessories"],
      ["Belt", "Accessories"],
      ["Medications", "Health"],
      ["First aid kit", "Health"],
    ]),
  },
  {
    id: "child1",
    name: "Child 1",
    avatar: "C1",
    photo: "/avatars/child1.jpg",
    items: createItems("child1", [
      ["T-shirts (5)", "Clothing"],
      ["Shorts (4)", "Clothing"],
      ["Swimsuits (2)", "Summer"],
      ["Pajamas (2)", "Clothing"],
      ["Underwear (7)", "Clothing"],
      ["Socks (5 pairs)", "Clothing"],
      ["Sneakers", "Clothing"],
      ["Sandals", "Clothing"],
      ["Swim goggles", "Summer"],
      ["Toothbrush", "Toiletries"],
      ["Kids shampoo", "Toiletries"],
      ["Sunscreen (SPF 50)", "Toiletries"],
      ["Tablet", "Electronics"],
      ["Tablet charger", "Electronics"],
      ["Books (2)", "Entertainment"],
      ["Card games", "Entertainment"],
    ]),
  },
  {
    id: "child2",
    name: "Child 2",
    avatar: "C2",
    photo: "/avatars/child2.jpg",
    items: createItems("child2", [
      ["Dresses (3)", "Clothing"],
      ["Tops (4)", "Clothing"],
      ["Shorts (3)", "Clothing"],
      ["Swimsuits (2)", "Summer"],
      ["Pajamas (2)", "Clothing"],
      ["Underwear (7)", "Clothing"],
      ["Socks (5 pairs)", "Clothing"],
      ["Sandals", "Clothing"],
      ["Sneakers", "Clothing"],
      ["Toothbrush", "Toiletries"],
      ["Kids shampoo", "Toiletries"],
      ["Sunscreen (SPF 50)", "Toiletries"],
      ["Hair ties & clips", "Accessories"],
      ["Coloring books", "Entertainment"],
      ["Crayons", "Entertainment"],
      ["Stuffed animal", "Entertainment"],
    ]),
  },
  {
    id: "child3",
    name: "Child 3",
    avatar: "C3",
    photo: "/avatars/child3.jpg",
    items: createItems("child3", [
      ["Onesies (5)", "Clothing"],
      ["Outfits (4)", "Clothing"],
      ["Pajamas (3)", "Clothing"],
      ["Socks (5 pairs)", "Clothing"],
      ["Sun hat", "Summer"],
      ["Swimsuit", "Summer"],
      ["Diapers", "Toiletries"],
      ["Wipes", "Toiletries"],
      ["Diaper cream", "Toiletries"],
      ["Baby shampoo", "Toiletries"],
      ["Baby sunscreen", "Toiletries"],
      ["Bottles", "Gear"],
      ["Sippy cup", "Gear"],
      ["Pacifiers", "Gear"],
      ["Blanket", "Bedding"],
      ["Stroller", "Gear"],
      ["Car seat", "Gear"],
      ["Favorite toy", "Toys"],
      ["Teething ring", "Toys"],
    ]),
  },
  {
    id: "child4",
    name: "Child 4",
    avatar: "C4",
    photo: "/avatars/child4.jpg",
    items: createItems("child4", [
      ["Onesies (5)", "Clothing"],
      ["Outfits (4)", "Clothing"],
      ["Pajamas (3)", "Clothing"],
      ["Socks (5 pairs)", "Clothing"],
      ["Sun hat", "Summer"],
      ["Swimsuit", "Summer"],
      ["Diapers", "Toiletries"],
      ["Wipes", "Toiletries"],
      ["Diaper cream", "Toiletries"],
      ["Baby shampoo", "Toiletries"],
      ["Baby sunscreen", "Toiletries"],
      ["Bottles", "Gear"],
      ["Sippy cup", "Gear"],
      ["Pacifiers", "Gear"],
      ["Blanket", "Bedding"],
      ["Favorite toy", "Toys"],
      ["Board books", "Toys"],
    ]),
  },
  {
    id: "gen-adults",
    name: "General Adults",
    avatar: "GA",
    photo: "/avatars/gen-adults.jpg",
    items: createItems("gen-adults", [
      ["Toiletry bag", "Toiletries"],
      ["Shared toothpaste", "Toiletries"],
      ["Travel towels", "Toiletries"],
      ["Power strip", "Electronics"],
      ["Portable charger", "Electronics"],
      ["Travel adapter", "Electronics"],
      ["Cash & cards", "Documents"],
      ["Insurance cards", "Documents"],
      ["Itinerary printout", "Documents"],
      ["Snack bars", "Snacks"],
      ["Trail mix", "Snacks"],
    ]),
  },
  {
    id: "gen-kids",
    name: "General Kids",
    avatar: "GK",
    photo: "/avatars/gen-kids.jpg",
    items: createItems("gen-kids", [
      ["Snack cups", "Snacks"],
      ["Juice boxes", "Snacks"],
      ["Goldfish crackers", "Snacks"],
      ["Fruit snacks", "Snacks"],
      ["Bug spray", "Safety"],
      ["After-bite cream", "Safety"],
      ["Band-aids", "Safety"],
      ["Portable high chair", "Gear"],
      ["Travel games", "Entertainment"],
      ["Coloring supplies", "Entertainment"],
      ["Sticker books", "Entertainment"],
    ]),
  },
]

export const initialMorningItems: PackingItem[] = [
  { id: "morning-1-empty-fridge", name: "Empty fridge", category: "General", status: "todo" },
  { id: "morning-2-take-out-trash", name: "Take out trash", category: "General", status: "todo" },
  { id: "morning-3-lock-up", name: "Lock all doors & windows", category: "General", status: "todo" },
  { id: "morning-4-set-alarm", name: "Set house alarm", category: "General", status: "todo" },
  { id: "morning-5-unplug-appliances", name: "Unplug appliances", category: "General", status: "todo" },
]
